// Code generated by Slice Machine. DO NOT EDIT.

import NavigationItem from './NavigationItem';
import TextBlock from './TextBlock';

export {
	NavigationItem,
	TextBlock,
};

export const components = {
	navbar: NavigationItem,
	text_block: TextBlock,
};
