// Code generated by Slice Machine. DO NOT EDIT.

import Navbar from './Navbar';
import TextBlock from './TextBlock';

export {
	Navbar,
	TextBlock,
};

export const components = {
	navbar: Navbar,
	text_block: TextBlock,
};
